import { addMonths } from "date-fns";
import { TransactionType } from "./column";
import {
  TRANSACTION_OPTIONS,
  TRANSACTION_FREQUENCY,
  TRANSACTION_STATUS,
} from "@/constants";

export const TRANSACTION_DATA: TransactionType[] = [
  {
    id: "txn_1",
    date: new Date(2023, 5, 15),
    title: "Freelance Payment",
    amount: 1200,
    type: TRANSACTION_OPTIONS.INCOME,
    category: "Freelance",
    status: TRANSACTION_STATUS.COMPLETED,
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 15), 1),
  },
  {
    id: "txn_2",
    date: new Date(2023, 5, 16),
    title: "Grocery Store",
    amount: 85.5,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Food",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 16), 1),
  },
  {
    id: "txn_3",
    date: new Date(2023, 5, 17),
    title: "Electric Bill",
    amount: 75.2,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Utilities",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 17), 1),
  },
  {
    id: "txn_4",
    date: new Date(2023, 5, 18),
    title: "Consulting Work",
    amount: 500,
    type: TRANSACTION_OPTIONS.INCOME,
    category: "Services",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 18), 1),
  },
  {
    id: "txn_5",
    date: new Date(2023, 5, 19),
    title: "Coffee Shop",
    amount: 4.75,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Food",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 19), 1),
  },
  {
    id: "txn_6",
    date: new Date(2023, 5, 20),
    title: "Online Course",
    amount: 89.99,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Education",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 20), 1),
  },
  {
    id: "txn_7",
    date: new Date(2023, 5, 21),
    title: "Rent Payment",
    amount: 950,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Housing",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 21), 1),
  },
  {
    id: "txn_8",
    date: new Date(2023, 5, 22),
    title: "Stock Dividends",
    amount: 42.5,
    type: TRANSACTION_OPTIONS.INCOME,
    category: "Investments",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 22), 1),
  },
  {
    id: "txn_9",
    date: new Date(2023, 5, 23),
    title: "Gym Membership",
    amount: 35,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Health",
    frequency: null,
    isRecurring: false,
  },
  {
    id: "txn_10",
    date: new Date(2023, 5, 24),
    title: "Book Sale",
    amount: 28.4,
    type: TRANSACTION_OPTIONS.INCOME,
    category: "Sales",
    frequency: null,
    isRecurring: false,
  },
  {
    id: "txn_11",
    date: new Date(2023, 5, 25),
    title: "Netflix Subscription",
    amount: 15.99,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Entertainment",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 25), 1),
  },
  {
    id: "txn_12",
    date: new Date(2023, 5, 26),
    title: "Salary Deposit",
    amount: 3000,
    type: TRANSACTION_OPTIONS.INCOME,
    category: "Salary",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 26), 1),
  },
  {
    id: "txn_13",
    date: new Date(2023, 5, 27),
    title: "Gym Membership",
    amount: 35,
    type: TRANSACTION_OPTIONS.EXPENSE,
    category: "Health",
    frequency: TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextOccurrence: addMonths(new Date(2023, 5, 27), 1),
  },
];
